# Generated by Django 3.2.4 on 2022-02-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0013_merge_0011_auto_20210701_0927_0012_client_created_at'),
        ('bookmarkmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetracker.client'),
        ),
    ]
