# Generated by Django 3.2.4 on 2021-06-21 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
