# Generated by Django 3.2.4 on 2021-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_auto_20210622_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='workinghours',
            field=models.TimeField(null=True),
        ),
    ]
