# Generated by Django 3.2.4 on 2021-06-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0004_workday_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='workinghours',
            field=models.DurationField(null=True),
        ),
    ]
