# Generated by Django 3.2.4 on 2021-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_alter_workday_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tusday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('day', 'customer')},
        ),
        migrations.AlterIndexTogether(
            name='workday',
            index_together=set(),
        ),
    ]
