# Generated by Django 3.2.4 on 2021-06-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0007_auto_20210623_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='workday',
            old_name='customer',
            new_name='client',
        ),
        migrations.AlterUniqueTogether(
            name='workday',
            unique_together={('day', 'client')},
        ),
    ]
