# Generated by Django 3.2.4 on 2021-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0008_auto_20210628_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_booking',
            field=models.BooleanField(default=True),
        ),
    ]
