# Generated by Django 3.2.4 on 2021-12-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0011_auto_20211220_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
