# Generated by Django 3.2.4 on 2021-12-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0011_auto_20210701_0927'),
        ('timetracker', '0012_client_created_at'),
    ]

    operations = [
    ]
